version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile   # Change this if your Dockerfile has a different name
    ports:
      - '3000:3000'            # Map host port to container port
    depends_on:
      - redis                  # Make sure the backend service starts after Redis
    environment:
      - NODE_ENV=production    # Set environment variables as needed
      - PORT=3000
      # Add more environment variables if necessary

  redis:
    image: redis:latest       # Use the latest Redis image
    ports:
      - '6379:6379'            # Map host port to container port
    volumes:
      - redis-data:/data       # Mount a volume for persistent Redis data

volumes:
  redis-data:                  # Define the volume for Redis data